openapi: 3.0.0
servers:
  - url: 'https://api.copper.co'
    description: ''
    variables: {}
info:
  version: 5aeeeffb-f864-4d25-bc8c-0bb43e95a77f
  title: Copper API
  description: ''
  termsOfService: ' '
  contact: {}
  license:
    name: ''
paths:
  /platform/accounts:
    get:
      summary: Get accounts
      operationId: Getaccounts
      parameters:
        - $ref: '#/components/parameters/X-Timestamp'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/X-Signature'
        - $ref: '#/components/parameters/Content-Type'
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - Accounts
  /platform/bank-accounts:
    get:
      summary: Get bank accounts
      operationId: Getbankaccounts
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - Accounts
  /platform/crypto-addresses:
    get:
      summary: Get crypto addresses
      operationId: Getcryptoaddresses
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - Accounts
  /platform/wallets:
    get:
      summary: Get wallets
      operationId: Getwallets
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - Accounts
  /platform/delegated-funds:
    get:
      summary: Get delegated funds
      operationId: Getdelegatedfunds
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - Accounts
    post:
      summary: Delegate funds
      operationId: Delegatefunds
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/vnd.update+json
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/vnd.update+json:
            schema:
              type: string
              example:
                requestId: '{{copperExternalId}}'
                portfolioId: 9dc6d4a1dd52bae94
                currency: BNB
                mainCurrency: BNB
                amount: 1
                delegateOrganizationId: PSHEOTC
            example: "{\n\t\"requestId\": \"{{copperExternalId}}\",\n\t\"portfolioId\": \"9dc6d4a1dd52bae94\",\n\t\"currency\": \"BNB\",\n\t\"mainCurrency\": \"BNB\",\n\t\"amount\": 1,\n\t\"delegateOrganizationId\": \"PSHEOTC\"\n}"
      tags:
        - Accounts
  /platform/managed-funds:
    get:
      summary: Get managed funds
      operationId: Getmanagedfunds
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - Accounts
  /platform/orders:
    get:
      summary: Get orders
      operationId: Getorders
      parameters:
        - $ref: '#/components/parameters/externalOrderId'
        - $ref: '#/components/parameters/updatedSince'
        - $ref: '#/components/parameters/portfolioId'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - Orders
    post:
      summary: Create order
      operationId: Createorder
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example:
                externalOrderId: '{{copperExternalId}}'
                orderType: withdraw
                baseCurrency: XRP
                mainCurrency: XRP
                amount: '10'
                portfolioId: '{{portfolioId}}'
                toAddress: '{{address}}'
            example: |-
              {
                  "externalOrderId": "{{copperExternalId}}",  
                  "orderType": "withdraw",
                  "baseCurrency": "XRP",
                  "mainCurrency": "XRP",
                  "amount": "10",
                  "portfolioId": "{{portfolioId}}",
                  "toAddress": "{{address}}"
              }
      tags:
        - Orders
  /platform/orders/{orderId}:
    get:
      summary: Get order
      operationId: Getorder
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
        - $ref: '#/components/parameters/orderId'
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - Orders
    patch:
      summary: Cancel order
      operationId: Cancelorder
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/vnd.cancel-order+json
        - name: orderId
          in: path
          required: true
          style: simple
          schema:
            type: string
            example: orderId
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/vnd.cancel-order+json:
            schema:
              type: string
              example: {}
            example: '{}'
      tags:
        - Orders
  /platform/wallet-messages:
    get:
      summary: Get messages
      operationId: Getmessages
      parameters:
        - name: externalOrderId
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: updatedSince
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: portfolioId
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: limit
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: offset
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - MessageSigning
    post:
      summary: Create message
      operationId: Createmessage
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example:
                externalMessageId: '{{copperExternalId}}'
                mainCurrency: XZC
                message: test
                portfolioId: '{{portfolioId}}'
            example: |-
              {
                  "externalMessageId": "{{copperExternalId}}",  
                  "mainCurrency": "XZC",
                  "message": "test",
                  "portfolioId": "{{portfolioId}}"
              }
      tags:
        - MessageSigning
  /platform/wallet-messages/{messageId}:
    get:
      summary: Get message
      operationId: Getmessage
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
        - $ref: '#/components/parameters/messageId'
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - MessageSigning
    patch:
      summary: Cancel message
      operationId: Cancelmessage
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/vnd.cancel-wallet-message+json
        - name: messageId
          in: path
          required: true
          style: simple
          schema:
            type: string
            example: messageId
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/vnd.cancel-wallet-message+json:
            schema:
              type: string
              example: {}
            example: '{}'
      tags:
        - MessageSigning
  /platform/proxy-wallets/:
    post:
      summary: Create proxy wallet
      operationId: Createproxywallet
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example:
                externalId: '{{copperExternalId}}'
                currency: XRP
                targetAddress: '{{address}}'
            example: |-
              {
                  "externalId": "{{copperExternalId}}",
                  "currency": "XRP",
                  "targetAddress": "{{address}}"
              }
      tags:
        - ProxyWallets
    get:
      summary: Get proxy wallets
      operationId: Getproxywallets
      parameters:
        - $ref: '#/components/parameters/currency'
        - $ref: '#/components/parameters/targetAddress'
        - $ref: '#/components/parameters/targetDestinationTag'
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - ProxyWallets
  /platform/proxy-wallets/{proxyWalletId}:
    get:
      summary: Get proxy wallet
      operationId: Getproxywallet
      parameters:
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
        - $ref: '#/components/parameters/proxyWalletId'
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - ProxyWallets
  /platform/proxy-transactions/:
    get:
      summary: Get proxy transacrtions
      operationId: Getproxytransacrtions
      parameters:
        - name: currency
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: updatedSince
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: limit
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: offset
          in: query
          required: true
          style: form
          schema:
            type: number
        - name: X-Timestamp
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperCurrentMillis}}'
        - name: Authorization
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: 'apikey {{copperApiKey}}'
        - name: X-Signature
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: '{{copperSignature}}'
        - name: Content-Type
          in: header
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers: {}
      tags:
        - ProxyWallets 
components:
  parameters:
    X-Timestamp:
      name: X-Timestamp
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: '{{copperCurrentMillis}}'
    Authorization:
      name: Authorization
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: 'apikey {{copperApiKey}}'
    X-Signature:
      name: X-Signature
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: '{{copperSignature}}'
    Content-Type:
      name: Content-Type
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: application/json
    externalOrderId:
      name: externalOrderId
      in: query
      required: true
      style: form
      schema:
        type: number
    updatedSince:
      name: updatedSince
      in: query
      required: true
      style: form
      schema:
        type: number
    portfolioId:
      name: portfolioId
      in: query
      required: true
      style: form
      schema:
        type: number
    limit:
      name: limit
      in: query
      required: true
      style: form
      schema:
        type: number
    offset:
      name: offset
      in: query
      required: true
      style: form
      schema:
        type: number
    orderId:
      name: orderId
      in: path
      required: true
      style: simple
      schema:
        type: string
        example: orderId
    messageId:
      name: messageId
      in: path
      required: true
      style: simple
      schema:
        type: string
        example: messageId
    proxyWalletId:
      name: proxyWalletId
      in: path
      required: true
      style: simple
      schema:
        type: string
        example: proxyWalletId
    currency:
      name: currency
      in: query
      required: true
      style: form
      schema:
        type: number
    targetAddress:
      name: targetAddress
      in: query
      required: true
      style: form
      schema:
        type: number
    targetDestinationTag:
      name: targetDestinationTag
      in: query
      required: true
      style: form
      schema:
        type: number
security: []
tags: []
externalDocs:
  url: 'https://docs.copper.co/'
  description: ''
warnings:
  - >-
    Two GET or two POST methods for the same path are not allowed in OpenAPI
    specification : post{{copperHost}}/platform/orders
  - >-
    Two GET or two POST methods for the same path are not allowed in OpenAPI
    specification : patch{{copperHost}}/platform/orders/{{orderId}}
  - >-
    Two GET or two POST methods for the same path are not allowed in OpenAPI
    specification : patch{{copperHost}}/platform/orders/{{orderId}}
  - >-
    Two GET or two POST methods for the same path are not allowed in OpenAPI
    specification : patch{{copperHost}}/platform/orders/{{orderId}}
  - >-
    Two GET or two POST methods for the same path are not allowed in OpenAPI
    specification : patch{{copperHost}}/platform/wallet-messages/{{messageId}}